[aws]
region = "eu-west-1"
access_key = "fake_key"
access_secret = "fake_secret"

[aws.dynamodb]
endpoint = "http://localhost:8042"
table_name = "eventstore"

[aws.sqs]
endpoint = "http://localhost:9324"

[postgres]
connection_string = "host=localhost port=5432 dbname=checkpoints user=es password=es sslmode=disable"

[projections]
queue_names = ["projections.fifo"]