name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.14'

      - name: setup test resources
        run: make setup

      - name: build and test
        run: |
          make mod
          make build
          make cover

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true